class IngramError:
    CONNECTION = "CONNECTION_ERROR"
    AUTH = "AUTHENTICATION_ERROR"
    SNAPSHOT = "SNAPSHOT_ERROR"
    POC = "POC_ERROR"
    FINGERPRINT = "FINGERPRINT_ERROR"
    PROTOCOL = "PROTOCOL_ERROR"
    TIMEOUT = "TIMEOUT_ERROR"
